### ISSUE TITLE
ROS Noetic

### ISSUE THREAD

**Issue by yani-rl-ai** [a-taniguchi/SpCoSLAM2#1]
could i run this package in ROS noetic?

**Comment by a-taniguchi** [comment]
A few changes are required, but you should be able to get it working.
For more information, this git repository would be suitable.
https://github.com/Shoichi-Hasegawa0628/spcoslam2

**Comment by yani-rl-ai** [comment]
hi @a-taniguchi many thanks for your help. i will try it soon.
